#!/bin/bash

## Remove Kubernetes Resources
kubectl delete statefulset consul nomad vault

kubectl delete persistentvolumeclaims \
  consul-data-consul-0 consul-data-consul-1 consul-data-consul-2 \
  consul-data-nomad-0 consul-data-nomad-1 consul-data-nomad-2 \
  consul-data-vault-0 \
  nomad-data-nomad-0 nomad-data-nomad-1 nomad-data-nomad-2

kubectl delete services consul consul-internal-load-balancer nomad vault

kubectl delete configmaps consul nomad vault

kubectl delete secrets consul nomad vault


## Remove GCP Resources
gcloud compute instance-groups managed delete -q nomad
gcloud compute instance-templates delete -q nomad-instance-template

gcloud container clusters delete -q nomad

gcloud compute firewall-rules delete -q \
  default-allow-consul \
  default-allow-nomad \
  default-allow-vault


