apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nomad
spec:
  serviceName: nomad
  replicas: 3
  template:
    metadata:
      labels:
        app: nomad
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nomad
              topologyKey: kubernetes.io/hostname
      containers:
        - name: nomad
          image: "gcr.io/hightowerlabs/nomad:0.6.0"
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nomad
                  key: vault-token
          args:
            - "agent"
            - "-config=/etc/nomad/nomad.d/server.hcl"
          ports:
            - name: http
              containerPort: 4646
              protocol: "TCP"
            - name: rpc
              containerPort: 4647
              protocol: "TCP"
            - name: serf-tcp
              containerPort: 4648
              protocol: "TCP"
            - name: serf-udp
              containerPort: 4648
              protocol: "UDP"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
          volumeMounts:
            - name: nomad-config
              mountPath: /etc/nomad/nomad.d
            - name: nomad-data
              mountPath: /var/lib/nomad
            - name: nomad-tls
              mountPath: /etc/nomad/tls
            - name: vault-tls
              mountPath: /etc/vault/tls
        - name: consul
          image: "consul:0.9.1"
          env:
            - name: GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul
                  key: gossip-encryption-key
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "agent"
            - "-config-file=/etc/consul/config/agent.json"
            - "-datacenter=dc1"
            - "-data-dir=/var/lib/consul"
            - "-disable-host-node-id"
            - "-domain=consul."
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
          resources:
            requests:
              cpu: "125m"
              memory: "512Mi"
          volumeMounts:
            - name: consul-config
              mountPath: /etc/consul/config
            - name: consul-data
              mountPath: /var/lib/consul
            - name: consul-tls
              mountPath: /etc/consul/tls
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
        - name: consul-config
          configMap:
            name: consul
        - name: consul-tls
          secret:
            secretName: consul
        - name: nomad-config
          configMap:
            name: nomad
        - name: nomad-tls
          secret:
            secretName: nomad
        - name: vault-tls
          secret:
            secretName: vault
  volumeClaimTemplates:
    - metadata:
        name: nomad-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: consul-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
