apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    name: vault
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8200
      protocol: "TCP"
    - name: server
      port: 8201
      protocol: "TCP"
  selector:
    app: vault
